version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: azureuser
      POSTGRES_PASSWORD: accenture-GRC-2025
      POSTGRES_DB: postgres-database
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    restart: always
    ports:
      - "8000:8000"

volumes:
  pg_data: